### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by Samson666** [sk-io/x86-multitasking-example#1]
Hi! I'd like to thank you for your (functioning!) multitasking project.
I was able to use your barebone for my own project.
Actually, i used it and built the rest of my own project around your code.
It would be nice, if you could make a little "how to" about your project :-)
So it is easyer to understand whats going on under the hood.
Anyways, greetings form Germany!
Regards Johannes

**Comment by sk-io** [comment]
Hey, glad it was useful to someone! That's a good idea, I'll see if I can add an overview/explanation to the README. I'll have to refresh my memory first though since I haven't touched this stuff in a while.

**Comment by Samson666** [comment]
Hi! Thank you for your really fast reply!
I'm really thankfull that i found your code after littaretly weeks of trial and error to get a working multitasking code. I had nightmares of "General Page Faults" and "Invalid Opcode" errors, i almost gave up. Luckylie i found your repository on github :-)
I also found your other projects on github and i'm really excited to learn more about OS-Developing.

If you don't mind, i'd like to ask you some question about your code. But before i bother you with my problems, i first ask if its OK.

Bye

Johannes

**Comment by sk-io** [comment]
Sure, go ahead!

**Comment by sk-io** [comment]
By the way, I wrote a simple overview of how it works in the README. I'm not the best at explaining things though so please tell me if it's too messy to understand.

**Comment by Samson666** [comment]
First of all, thank you for your reply. I really appreciate it.

Your new Readme is explaining a lot of questions i was going to ask you.
So if i understand that correctly, the kernel stack given to the task is just for creating a new task and while the task is running the user stack is used?

My next question would be: creating a new task with the "kernel" argument lets the task running in ring0? So i tested to put a "Halt" directive in a "user" labeled task and i would expect a "General Protection fault" or something like that. But that doesn't happen. Do i need to define a fault handler my self?

And for the last of my stupid questions: do i see it correctly that a software IRQ 0x80 should launch a syscall which i can use to call functions of the ring0 out of a ring3 task? Could you give me a little example how to handle such a syscall?

Many thanks for your patience for my noob-questions :-)

Regards
Johannes

**Comment by sk-io** [comment]
These are good questions!

No, the kernel stacks given to tasks are used when interrupts occur while that task is running. Then, when an interrupt occurs (usually a PIT interrupt) and we want to switch tasks, we just leave that kernel stack with our registers pushed to it so we can return to it later. Then we switch to the next kernel stack and pop from it. Which then returns from whatever interrupt that one was suspended in, back to where it was executing.

This project doesn't have any print functionality but you should get a GPR, which is interrupt no 13. I can't test that right now though.

Yes, syscalls and shared memory(via paging) are the primary ways for x86 userspace programs to communicate with the kernel. You can pass arguments to syscalls using the GP registers, since the interrupt handler captures the state of these. In this project,  you can access these in handle_interrupt via TrapFrame (using cdecl, arguments are passed via the stack). Usually EAX is used for specifying the syscall number, then EBX, ECX, etc.. can be used for other arguments. To pass back a return value, you can modify EAX in the trap frame before returning from the interrupt.

Heres an example of how I implemented syscalls in my other project:
https://github.com/sk-io/os/blob/9a4a5287ad2e8d3dd91032d66e64f6a57567ccbc/kernel/syscall.c#L235

**Comment by Samson666** [comment]
Hi. Hope you are doing well.

Thank you for your explanations. Now it's almost clear to me whats happening :-)
I was able to write a simple fault handler and it now catches the IRQ13. 
But i was wondering why it is throwing an IRQ6 as soon as i enable taskswitching. I guess it happens while calling the schedule routine. So far i just ignore IRQ6 but that is a little bit unsatisfactory.
Maybe it's because i am compiling with the i386-elf-gcc? I tried to switch off sse and mmx for gcc but then i can't use floating point anymore :-(
Maybe you have an idea whats going on.

Johannes

**Comment by sk-io** [comment]
Are you familiar with GDB? Since there's no logging functionality I think that's the easiest way to debug these kinds of low level problems. Also, are you on Linux?

**Comment by sk-io** [comment]
Also, make sure that the tasks end in an infinite loop, otherwise they just continue executing garbage code after leaving their entry functions. A better solution might be to have a syscall to exit the current task.

I should probably leave a comment about that..

**Comment by Samson666** [comment]
Hi! As always, thank you for your really fast reply!
I will take a look into GDB. I've heard of it, but to this time i was not really interested in debugging. Shame on me :-)
I was able to compile and run your "Untitled OS" using gcc (compiler and linker). One thing bothers me a little bit, in printf it says it can't find some 32 to 64bit functions. Obviously i am using the wrong gcclib. Maybe you have tip for me. For now i disabled the long_long_print function and it works fine.

Maybe i have one tip for you, but i guess you already know this:
In your "Untitled OS" you should use "qemu-system-i386 -cdrom $(IMAGE) -machine accel=kvm -serial stdio".
It runs way faster with the kvm acceleration.

**Comment by sk-io** [comment]
Hey, thanks for checking it out! I'm surprised you got it to build using GCC though, I switched to clang on that project cause of some issues with shared libraries. And yeah you need a 32-bit libgcc (not libc, that's implemented in userspace/libc) if that's what you're referring to. Maybe open an issue there with details instead?

Yeah I know about KVM, it didn't work on my system though for whatever reason. I'll check it out again when I've got time :)

**Comment by Samson666** [comment]
Aaargh! You were right. I did only change the main-makefile to use gcc. The other makefiles were using clang :-) With gcc i get a pagefault when loading the api.so file. Strange behaviour though.

Cheers
Johannes

**Comment by Samson666** [comment]
Btw. I'd like to make a copy of your repository to my github space. I hope that is ok for you.

**Comment by sk-io** [comment]
Sure! Do whatever you want :) These are just learning/hobby projects.

**Comment by Samson666** [comment]
Hi there! Fixed the libgcc problem :-)
I put -lgcc in the gcc compiler flags but then i found out that if you do that you have to use gcc
as linker too. So i had to add the libgcc to ld and now it works fine.
Have a great sunday!
Cheers
Johannes

**Comment by sk-io** [comment]
Oh, I thought you were talking about the other project. Yeah, I think it's always preferable to use gcc for linking intead of ld, I'll change that. Thanks and cheers to you too!

**Comment by Samson666** [comment]
Oh, another question just came to my mind...
In your taskswitching asm code in both of the projects you are using the "ret" command instead of the "iretl" command which i thought should be used to return from an interrupt.

**Comment by sk-io** [comment]
It's not immediately exiting from the interrupt in switch_context if that's what you mean. It follows the stack back down until it reaches [this point](https://github.com/sk-io/x86-multitasking-example/blob/8daf9e85e6f95fdaef97fae83676bc87a6cf0c5f/kernel_asm.asm#L59), where it returns from the interrupt.

**Comment by Samson666** [comment]
Thank you! I just realized that the Timer-IRQ is calling switch_context.
I really appreciate your fast replies and your endless knowledge on how to program.
I just hope that i am not too annoying with my noob questions.
Best wishes from Germany
Johannes

**Comment by sk-io** [comment]
No problem! You're helping me refresh my memory aswell :)
